# Generated by Django 2.0.13 on 2019-09-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190913_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='route',
            new_name='title',
        ),
    ]
