# Generated by Django 2.0.13 on 2019-09-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190913_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='train',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
