# Generated by Django 2.0.13 on 2019-09-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
