# Generated by Django 2.0.13 on 2019-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='train',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
