# Generated by Django 2.0.13 on 2019-09-24 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190919_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.IntegerField()),
                ('landmark', models.CharField(max_length=30)),
                ('train1', models.CharField(max_length=15)),
                ('time1', models.DateTimeField(default=django.utils.timezone.now)),
                ('train2', models.CharField(max_length=15)),
                ('time2', models.DateTimeField(default=django.utils.timezone.now)),
                ('train3', models.CharField(max_length=15)),
                ('time3', models.DateTimeField(default=django.utils.timezone.now)),
                ('train4', models.CharField(max_length=15)),
                ('time4', models.DateTimeField(default=django.utils.timezone.now)),
                ('train5', models.CharField(max_length=15)),
                ('time5', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
