# Generated by Django 2.0.13 on 2019-09-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190924_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='train1',
            field=models.CharField(choices=[('marunouti', '東京メトロ丸ノ内線'), ('hukutosi', '東京メトロ副都心線'), ('sinjuku', '都営新宿線'), ('ooedo', '都営大江戸線'), ('yamanote', 'JR山手線'), ('soumu', 'JR総武線'), ('saikyou', 'JR埼京線'), ('tyuou', 'JR中央線'), ('tyuouhon', 'JR中央本線'), ('syounansinjuku', '湘南新宿ライン'), ('keiou', '京王線'), ('keiousin', '京王新線'), ('odakyuuodawara', '小田急小田原線'), ('seibusinjuku', '西武新宿線')], default='marunouti', max_length=15),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='train2',
            field=models.CharField(choices=[('marunouti', '東京メトロ丸ノ内線'), ('hukutosi', '東京メトロ副都心線'), ('sinjuku', '都営新宿線'), ('ooedo', '都営大江戸線'), ('yamanote', 'JR山手線'), ('soumu', 'JR総武線'), ('saikyou', 'JR埼京線'), ('tyuou', 'JR中央線'), ('tyuouhon', 'JR中央本線'), ('syounansinjuku', '湘南新宿ライン'), ('keiou', '京王線'), ('keiousin', '京王新線'), ('odakyuuodawara', '小田急小田原線'), ('seibusinjuku', '西武新宿線')], default='marunouti', max_length=15),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='train3',
            field=models.CharField(choices=[('marunouti', '東京メトロ丸ノ内線'), ('hukutosi', '東京メトロ副都心線'), ('sinjuku', '都営新宿線'), ('ooedo', '都営大江戸線'), ('yamanote', 'JR山手線'), ('soumu', 'JR総武線'), ('saikyou', 'JR埼京線'), ('tyuou', 'JR中央線'), ('tyuouhon', 'JR中央本線'), ('syounansinjuku', '湘南新宿ライン'), ('keiou', '京王線'), ('keiousin', '京王新線'), ('odakyuuodawara', '小田急小田原線'), ('seibusinjuku', '西武新宿線')], default='marunouti', max_length=15),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='train4',
            field=models.CharField(choices=[('marunouti', '東京メトロ丸ノ内線'), ('hukutosi', '東京メトロ副都心線'), ('sinjuku', '都営新宿線'), ('ooedo', '都営大江戸線'), ('yamanote', 'JR山手線'), ('soumu', 'JR総武線'), ('saikyou', 'JR埼京線'), ('tyuou', 'JR中央線'), ('tyuouhon', 'JR中央本線'), ('syounansinjuku', '湘南新宿ライン'), ('keiou', '京王線'), ('keiousin', '京王新線'), ('odakyuuodawara', '小田急小田原線'), ('seibusinjuku', '西武新宿線')], default='marunouti', max_length=15),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='train5',
            field=models.CharField(choices=[('marunouti', '東京メトロ丸ノ内線'), ('hukutosi', '東京メトロ副都心線'), ('sinjuku', '都営新宿線'), ('ooedo', '都営大江戸線'), ('yamanote', 'JR山手線'), ('soumu', 'JR総武線'), ('saikyou', 'JR埼京線'), ('tyuou', 'JR中央線'), ('tyuouhon', 'JR中央本線'), ('syounansinjuku', '湘南新宿ライン'), ('keiou', '京王線'), ('keiousin', '京王新線'), ('odakyuuodawara', '小田急小田原線'), ('seibusinjuku', '西武新宿線')], default='marunouti', max_length=15),
        ),
    ]
